In [36]:
from unittest import main
import numpy as np

In [37]:
def calculate(list):
    if len(list) != 9:
        raise ValueError("List must have 9 numbers")
    
    calculations = {}
    array = np.array(list).reshape(3,3)
    
    mean = []
    mean.append(array.mean(axis=0))
    mean.append(array.mean(axis=1))
    mean.append(array.mean())
    calculations['mean'] = [mean]

    variance = []
    variance.append(array.var(axis=0))
    variance.append(array.var(axis=1))
    variance.append(array.var())
    calculations['variance'] = [variance]

    deviation = []
    deviation.append(array.std(axis=0))
    deviation.append(array.std(axis=1))
    deviation.append(array.std())
    calculations['standard deviation'] = [deviation]
    
    max = []
    max.append(array.max(axis=0))
    max.append(array.max(axis=1))
    max.append(array.max())
    calculations['max'] = [max]

    min = []
    min.append(array.min(axis=0))
    min.append(array.min(axis=1))
    min.append(array.min())
    calculations['min'] = [min]

    sum = []
    sum.append(array.sum(axis=0))
    sum.append(array.sum(axis=1))
    sum.append(array.sum())
    calculations['sum'] = [sum]

    return calculations

calculate([2,6,2,8,4,0,1,5,7])

{'mean': [[array([3.66666667, 5.        , 3.        ]),
   array([3.33333333, 4.        , 4.33333333]),
   3.888888888888889]],
 'variance': [[array([9.55555556, 0.66666667, 8.66666667]),
   array([ 3.55555556, 10.66666667,  6.22222222]),
   6.987654320987654]],
 'standard deviation': [[array([3.09120617, 0.81649658, 2.94392029]),
   array([1.88561808, 3.26598632, 2.49443826]),
   2.6434171674156266]],
 'max': [[array([8, 6, 7]), array([6, 8, 7]), 8]],
 'min': [[array([1, 4, 0]), array([2, 0, 1]), 0]],
 'sum': [[array([11, 15,  9]), array([10, 12, 13]), 35]]}